# Voice Assistant Configuration

voice:
  language: tr-TR
  timeout: 5
  ambient_duration: 1
  energy_threshold: 4000
  pause_threshold: 0.8
  non_speaking_duration: 0.5
  dynamic_energy_threshold: true

# Recognition settings
recognition:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  max_retries: 3
  retry_delay: 1.0

# GUI settings
gui:
  theme: dark
  window_title: "Lazzaran - Türkçe Sesli Asistan"
  window_size:
    width: 800
    height: 600
  opacity: 0.95

# Logging settings
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: lazzaran.log

# Service settings
services:
  weather:
    update_interval: 1800  # 30 minutes
    default_city: "Istanbul"
  
  news:
    update_interval: 3600  # 1 hour
    max_articles: 10
    categories:
      - general
      - technology
      - business
  
  ai:
    model: "gemini-pro"
    temperature: 0.7
    max_tokens: 1000
    context_length: 10

commands:
  - google
  - youtube
  - hava durumu
  - saat
  - kapat
  - yeniden başlat
  - hesap makinesi
  - haberler
  - haber ara
  - sohbet 